# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Concrete' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Concrete
  pod 'Firebase/Core', '~> 5.20.2'
  pod 'Firebase/Auth', '~> 5.20.2'
  # pod 'Firebase/Firestore', '~> 5.20.2'
  # pod 'Firebase/Storage', '~> 5.20.2'
  pod 'Firebase/Database', '~> 5.20.2'
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"



  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
